/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 coin.gltf 
Author: alex.yefremov (https://sketchfab.com/alex.yefremov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gold-coin-f2481a0614b84f4da33c481f3d9af1ac
Title: gold coin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/coin.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.pCylinder1_lambert1_0.geometry} material={materials.lambert1} rotation={[-Math.PI / 2, 0, 0]} scale={[14.994, 0.87, 14.994]} />
      </group>
    </group>
  )
}

useGLTF.preload('/coin.gltf')
